# Generated by Django 3.2.7 on 2022-01-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220105_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(db_index=True, default=0, max_length=200, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
