# Generated by Django 3.2.7 on 2022-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220106_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderate',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('slug',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
