# Generated by Django 3.2.7 on 2022-02-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220211_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profie',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
    ]
