# Generated by Django 3.2.7 on 2022-02-13 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_profie_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something', models.CharField(max_length=225, verbose_name='Что-то')),
            ],
        ),
        migrations.RenameModel(
            old_name='Profie',
            new_name='Profile',
        ),
    ]
