# Generated by Django 3.2.7 on 2022-02-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
