# Generated by Django 3.2.7 on 2022-02-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='users',
        ),
    ]
