# Generated by Django 3.2.7 on 2022-03-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='moderate',
        ),
    ]
