# Generated by Django 3.2.7 on 2022-03-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderate',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='Категория'),
        ),
    ]
