# Generated by Django 3.2.7 on 2022-03-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20220304_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер'),
        ),
    ]
